on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ^1.20
      - uses: golangci/golangci-lint-action@v3
        name: golangci-lint
        with:
          version: v1.51.2
      - run: go test -count=1 -v ./...
